<script type="text/javascript" src="assets/js/jquery.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.4/lodash.min.js"></script>
<script type="text/javascript" src="assets/js/bootstrap.js"></script>
<script type="text/javascript" src="assets/js/url.js"></script>
<script type="text/javascript" src="assets/js/main.js"></script>
<script type="text/javascript" src="assets/js/toastr.min.js"></script>
<script type="text/javascript" src="assets/js/categories.js"></script>
<script type="text/javascript" src="assets/js/products.js"></script>
<script type="text/javascript" src="assets/js/easyValidate.js"></script>
<script type="text/javascript" src="assets/js/eventKey.js"></script>